### ISSUE TITLE
Avoid running plugins two times if a preload script is present

### ISSUE THREAD

**Issue by GeorgianStan** [electron-forge/electron-forge-docs#15]
If a preload script is used.

```
 "plugins": [
        [
          "@electron-forge/plugin-webpack",
          {
            "mainConfig": "./webpack.main.config.js",
            "renderer": {
              "config": "./webpack.renderer.config.js",
              "entryPoints": [
                {
                  "html": "./src/renderer/index.html",
                  "js": "./src/renderer/index.ts",
                  "name": "main_window",
                  "preload": {
                    "js": "./src/main/preload.ts"
                  }
                }
              ]
            }
          }
        ]
      ]
```

then the plugins from `webpack.renderer.config.js` will run twice. For example if a copy files plugin is used

```
 new CopyPlugin({
      patterns: [{ from: "./src/renderer/assets", to: "assets" }],
    }),
```
Then the assets folder will be copied twice:
- .webpack/renderer/assets
- .webpack/renderer/main_window/assets

Can this problem be overcome?

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
